"""
DevOps Office — Deployer

Takes the completed codebase and:
1. Writes all files to a local sandbox directory
2. Generates REPORT.md (execution summary)
3. Creates a GitHub repo via PyGithub
4. Pushes the code via GitPython
"""

import os

import json
import shutil
import time
from pathlib import Path
from colorama import Fore, Style
from github import Github, GithubException
from git import Repo as GitRepo

from ..state import OfficeState
from ..config import GITHUB_TOKEN, GITHUB_OWNER, SANDBOX_DIR
from ..logger import get_logger

logger = get_logger("devops")


def _generate_report(state: OfficeState, total_elapsed: float) -> str:
    """Generate a REPORT.md summarizing the entire pipeline run."""
    codebase = state.get("codebase", {})
    tech_stack = state.get("tech_stack", {})
    logs = state.get("execution_logs", [])

    lines = [
        "# AI Office Chain — Execution Report",
        "",
        "This project was auto-generated by the **AI Office Chain** pipeline.",
        "",
        "## Project",
        "",
        f"- **Goal**: {state.get('project_goal', 'N/A')}",
        f"- **Name**: {state.get('project_name', 'N/A')}",
        f"- **Total Time**: {total_elapsed:.1f}s",
        f"- **Files Generated**: {len(codebase)}",
        "",
        "## Tech Stack",
        "",
    ]

    if tech_stack:
        for key, val in tech_stack.items():
            if isinstance(val, list):
                lines.append(f"- **{key}**: {', '.join(val)}")
            else:
                lines.append(f"- **{key}**: {val}")
    else:
        lines.append("- (not specified)")

    lines += [
        "",
        "## Files Created",
        "",
    ]

    for filepath in codebase:
        size = len(codebase[filepath])
        lines.append(f"- `{filepath}` ({size} chars)")

    lines += [
        "",
        "## Execution Log",
        "",
    ]

    for log_entry in logs:
        lines.append(f"- {log_entry}")

    lines += [
        "",
        "---",
        "",
        "*Generated by [AI Office Chain](https://github.com/Nakul-Sinha/griffin_personal) — "
        "a sequential multi-agent LangGraph pipeline.*",
        "",
    ]

    return "\n".join(lines)


def devops_office(state: OfficeState) -> dict:
    """DevOps node: write files locally, generate report, and push to GitHub."""

    logger.info("=== DEVOPS OFFICE — Entering ===")
    logger.info(
        f"Input state: project_name='{state['project_name']}', "
        f"files_in_codebase={len(state.get('codebase', {}))}"
    )
    office_start = time.time()

    print(f"\n{Fore.RED}{'='*60}")
    print(f"  🚀  DEVOPS OFFICE — Deployer")
    print(f"{'='*60}{Style.RESET_ALL}\n")

    project_name = state["project_name"]
    codebase = state.get("codebase", {})
    logs: list[str] = []

    if not codebase:
        msg = "[DEVOPS] ERROR: No codebase to deploy!"
        logger.error(msg)
        print(f"  {Fore.RED}❌ {msg}{Style.RESET_ALL}")
        return {"execution_logs": [msg]}

    # ── Step 1: Write files to sandbox ──────────────────────────
    project_dir = SANDBOX_DIR / project_name
    
    # Remove existing directory with proper error handling for Windows
    if project_dir.exists():
<<<<<<< Updated upstream
        def _force_remove_readonly(func, path, _exc_info):
            """Windows: clear read-only flag on .git files before retrying."""
            os.chmod(path, 0o777)
            func(path)
        shutil.rmtree(project_dir, onerror=_force_remove_readonly)
=======
        try:
            # On Windows, we need to handle read-only files and git objects
            def handle_remove_readonly(func, path, exc):
                """Error handler for Windows readonly files."""
                import os
                import stat
                if not os.access(path, os.W_OK):
                    os.chmod(path, stat.S_IWUSR)
                    func(path)
                else:
                    raise
            
            shutil.rmtree(project_dir, onerror=handle_remove_readonly)
        except Exception as e:
            logger.warning(f"Could not remove existing directory: {e}")
            # Try alternative: rename old directory and create new one
            import random
            backup_name = f"{project_name}_old_{random.randint(1000, 9999)}"
            backup_dir = SANDBOX_DIR / backup_name
            project_dir.rename(backup_dir)
            logger.info(f"Renamed old directory to {backup_name}")
    
>>>>>>> Stashed changes
    project_dir.mkdir(parents=True, exist_ok=True)

    print(f"  {Fore.CYAN}📁 Writing files to:{Style.RESET_ALL} {project_dir}\n")
    logger.info(f"Writing {len(codebase)} files to {project_dir}")

    for filepath, content in codebase.items():
        full_path = project_dir / filepath
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
        print(f"     ✅ {filepath}")
        logs.append(f"[DEVOPS] Wrote {filepath}")

    print(f"\n  {Fore.GREEN}✅ All {len(codebase)} files written locally.{Style.RESET_ALL}\n")

    # ── Step 2: Generate REPORT.md ──────────────────────────────
    # Calculate approximate total elapsed (from first log timestamp)
    office_elapsed_so_far = time.time() - office_start
    # Use a rough estimate — we'll update after git push
    report_content = _generate_report(state, total_elapsed=0)
    report_path = project_dir / "REPORT.md"
    report_path.write_text(report_content, encoding="utf-8")
    print(f"  {Fore.CYAN}📝 Generated REPORT.md{Style.RESET_ALL}")
    logger.info("Generated REPORT.md in project directory")
    logs.append("[DEVOPS] Generated REPORT.md")

    # ── Step 3: Create GitHub repo ──────────────────────────────
    github_url = ""

    if not GITHUB_TOKEN or not GITHUB_OWNER:
        msg = (
            "[DEVOPS] GITHUB_TOKEN or GITHUB_OWNER not set. "
            "Skipping GitHub push. Files are in sandbox/."
        )
        print(f"  {Fore.YELLOW}⚠️  {msg}{Style.RESET_ALL}")
        logger.warning(msg)
        logs.append(msg)

        # Update REPORT.md with final timing
        office_elapsed = time.time() - office_start
        report_content = _generate_report(state, total_elapsed=office_elapsed)
        report_path.write_text(report_content, encoding="utf-8")

        return {"github_url": "", "execution_logs": logs}

    try:
        print(f"  {Fore.CYAN}🔗 Creating GitHub repo...{Style.RESET_ALL}")
        logger.info("Creating GitHub repo...")
        g = Github(GITHUB_TOKEN)
        user = g.get_user()

        # Try to create the repo (if it already exists, we'll use it)
        try:
            repo = user.create_repo(
                project_name,
                description=f"Generated by AI Office Chain: {state['project_goal'][:100]}",
                private=False,
                auto_init=False,
            )
            print(f"  {Fore.GREEN}✅ Repo created:{Style.RESET_ALL} {repo.html_url}")
            logger.info(f"Repo created: {repo.html_url}")
        except GithubException as e:
            if e.status == 422:  # Already exists
                repo = user.get_repo(project_name)
                print(f"  {Fore.YELLOW}⚠️  Repo exists, using:{Style.RESET_ALL} {repo.html_url}")
                logger.info(f"Repo already exists, using: {repo.html_url}")
            else:
                raise

        github_url = repo.html_url
        logs.append(f"[DEVOPS] GitHub repo: {github_url}")

        # ── Step 4: Update REPORT.md with final timing + git push ─
        office_elapsed = time.time() - office_start
        report_content = _generate_report(state, total_elapsed=office_elapsed)
        report_path.write_text(report_content, encoding="utf-8")

        print(f"  {Fore.CYAN}📤 Pushing to GitHub...{Style.RESET_ALL}")
        logger.info("Initializing git and pushing...")

        git_repo = GitRepo.init(project_dir)
        # Force-add every generated file (bypasses the project's .gitignore)
        for filepath in codebase:
            git_repo.git.add(filepath, force=True)
        git_repo.git.add("REPORT.md", force=True)
        git_repo.index.commit("🚀 Initial commit — generated by AI Office Chain")

        # Set up remote
        remote_url = f"https://{GITHUB_TOKEN}@github.com/{GITHUB_OWNER}/{project_name}.git"

        if "origin" in [r.name for r in git_repo.remotes]:
            git_repo.delete_remote("origin")
        origin = git_repo.create_remote("origin", remote_url)

        # Push
        origin.push(refspec="HEAD:refs/heads/main", force=True)

        print(f"  {Fore.GREEN}✅ Pushed successfully!{Style.RESET_ALL}")
        logger.info(f"Pushed to {github_url}")
        logs.append(f"[DEVOPS] Pushed to {github_url}")

    except Exception as e:
        msg = f"[DEVOPS] GitHub error: {str(e)}"
        print(f"  {Fore.RED}❌ {msg}{Style.RESET_ALL}")
        logger.error(msg)
        logs.append(msg)

    # ── Summary ─────────────────────────────────────────────────
    office_elapsed = time.time() - office_start
    logger.info(
        f"=== DEVOPS OFFICE — Exiting ({office_elapsed:.2f}s) | "
        f"github_url='{github_url}' ==="
    )

    print(f"\n  {Fore.GREEN}{'─'*50}")
    if github_url:
        print(f"  🎉 Project deployed: {github_url}")
    else:
        print(f"  📁 Project saved locally: {project_dir}")
    print(f"  {'─'*50}{Style.RESET_ALL}\n")

    return {
        "github_url": github_url,
        "execution_logs": logs,
    }
