"""
DevOps Office — Deployer

Takes the completed codebase and:
1. Writes all files to a local sandbox directory
2. Creates a GitHub repo via PyGithub
3. Pushes the code via GitPython
"""

import os
import shutil
from pathlib import Path
from colorama import Fore, Style
from github import Github, GithubException
from git import Repo as GitRepo

from ..state import OfficeState
from ..config import GITHUB_TOKEN, GITHUB_OWNER, SANDBOX_DIR


def devops_office(state: OfficeState) -> dict:
    """DevOps node: write files locally and push to GitHub."""

    print(f"\n{Fore.RED}{'='*60}")
    print(f"  🚀  DEVOPS OFFICE — Deployer")
    print(f"{'='*60}{Style.RESET_ALL}\n")

    project_name = state["project_name"]
    codebase = state.get("codebase", {})
    logs: list[str] = []

    if not codebase:
        msg = "[DEVOPS] ERROR: No codebase to deploy!"
        print(f"  {Fore.RED}❌ {msg}{Style.RESET_ALL}")
        return {"execution_logs": [msg]}

    # ── Step 1: Write files to sandbox ──────────────────────────
    project_dir = SANDBOX_DIR / project_name
    if project_dir.exists():
        shutil.rmtree(project_dir)
    project_dir.mkdir(parents=True, exist_ok=True)

    print(f"  {Fore.CYAN}📁 Writing files to:{Style.RESET_ALL} {project_dir}\n")

    for filepath, content in codebase.items():
        full_path = project_dir / filepath
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
        print(f"     ✅ {filepath}")
        logs.append(f"[DEVOPS] Wrote {filepath}")

    print(f"\n  {Fore.GREEN}✅ All {len(codebase)} files written locally.{Style.RESET_ALL}\n")

    # ── Step 2: Create GitHub repo ──────────────────────────────
    github_url = ""

    if not GITHUB_TOKEN or not GITHUB_OWNER:
        msg = (
            "[DEVOPS] GITHUB_TOKEN or GITHUB_OWNER not set. "
            "Skipping GitHub push. Files are in sandbox/."
        )
        print(f"  {Fore.YELLOW}⚠️  {msg}{Style.RESET_ALL}")
        logs.append(msg)
        return {"github_url": "", "execution_logs": logs}

    try:
        print(f"  {Fore.CYAN}🔗 Creating GitHub repo...{Style.RESET_ALL}")
        g = Github(GITHUB_TOKEN)
        user = g.get_user()

        # Try to create the repo (if it already exists, we'll use it)
        try:
            repo = user.create_repo(
                project_name,
                description=f"Generated by AI Office Chain: {state['project_goal'][:100]}",
                private=False,
                auto_init=False,
            )
            print(f"  {Fore.GREEN}✅ Repo created:{Style.RESET_ALL} {repo.html_url}")
        except GithubException as e:
            if e.status == 422:  # Already exists
                repo = user.get_repo(project_name)
                print(f"  {Fore.YELLOW}⚠️  Repo exists, using:{Style.RESET_ALL} {repo.html_url}")
            else:
                raise

        github_url = repo.html_url
        logs.append(f"[DEVOPS] GitHub repo: {github_url}")

        # ── Step 3: Git init, commit, push ──────────────────────
        print(f"  {Fore.CYAN}📤 Pushing to GitHub...{Style.RESET_ALL}")

        git_repo = GitRepo.init(project_dir)
        git_repo.git.add(A=True)
        git_repo.index.commit("🚀 Initial commit — generated by AI Office Chain")

        # Set up remote
        remote_url = f"https://{GITHUB_TOKEN}@github.com/{GITHUB_OWNER}/{project_name}.git"

        if "origin" in [r.name for r in git_repo.remotes]:
            git_repo.delete_remote("origin")
        origin = git_repo.create_remote("origin", remote_url)

        # Push
        origin.push(refspec="HEAD:refs/heads/main", force=True)

        print(f"  {Fore.GREEN}✅ Pushed successfully!{Style.RESET_ALL}")
        logs.append(f"[DEVOPS] Pushed to {github_url}")

    except Exception as e:
        msg = f"[DEVOPS] GitHub error: {str(e)}"
        print(f"  {Fore.RED}❌ {msg}{Style.RESET_ALL}")
        logs.append(msg)

    # ── Summary ─────────────────────────────────────────────────
    print(f"\n  {Fore.GREEN}{'─'*50}")
    if github_url:
        print(f"  🎉 Project deployed: {github_url}")
    else:
        print(f"  📁 Project saved locally: {project_dir}")
    print(f"  {'─'*50}{Style.RESET_ALL}\n")

    return {
        "github_url": github_url,
        "execution_logs": logs,
    }
